language: node_js

node_js:
  - "6.1"

env:
  global:
    - GIT_NAME="Shafiq Alibhai"
    - GIT_EMAIL="email@shafiq.in"
    - GIT_USERNAME=$username
    - GIT_PASSWORD=$password

before_script:
  - npm install npm -g
  - npm install bower -g
  - npm install gulp -g
  - git remote set-url origin https://$GIT_USERNAME:$GIT_PASSWORD@github.com/shafiqissani/www.deployview.co.uk.git
  - git config --global user.name "$GIT_NAME"
  - git config --global user.email "$GIT_EMAIL"

script:
  - gulp build
  - git clone https://$GIT_USERNAME:$GIT_PASSWORD@github.com/shafiqissani/www.deployview.co.uk.git gh-pages
  - cd gh-pages
  - git checkout gh-pages
  - cd ..
  - cd dist
  - mv * ../gh-pages/
  - cd ..
  - cd gh-pages
  - git add -A .
  - git commit --allow-empty -m "Deployed by Travis"
  - git push -u origin gh-pages --force | true
