language: node_js

node_js:
  - "6.1"

env:
  global:
    - SSH_KEY="id_rsa"
    - GIT_NAME="Shafiq Alibhai"
    - GIT_EMAIL="email@shafiq.in"

before_script:
  - npm install npm -g
  - npm install bower -g
  - npm install gulp -g
  - git remote set-url origin https://$username:$password@github.com/shafiqissani/www.deployview.co.uk.git
  - ls -la

script:
  - gulp build
  - cd dist
  - git init
  - git remote add origin https://$username:$password@github.com/shafiqissani/www.deployview.co.uk.git
  - git add -A .
  - git commit --allow-empty -m "Deployed by Travis"
  - git status
